# Temperate fruits
*by [Eike Luedeling](http://www.hortibonn.de/author/prof.-dr.-eike-luedeling/), [Christine Schmitz](http://www.hortibonn.de/author/christine-schmitz/), [Eduardo Fernandez](https://www.pucv.cl/uuaa/escuela-de-agronomia/eduardo-fernandez-collao) and [Anton Milyaev](http://inresgb-lehre.iaas.uni-bonn.de/author/dr.-anton-milyaev/)*

## Materials

To prepare for class, please watch the following four videos:

* [General concepts](https://uni-bonn.sciebo.de/s/yKN9dy7xNkmXQTg) (password [here](https://ecampus.uni-bonn.de/goto_ecampus_copa_3530257.html))
* [Nuts](https://uni-bonn.sciebo.de/s/hh7O7y95krrVFLg) (password [here](https://ecampus.uni-bonn.de/goto_ecampus_copa_3530257.html))
* [Stone fruits](https://uni-bonn.sciebo.de/s/Wb8pk3fbMRjUU41) (password [here](https://ecampus.uni-bonn.de/goto_ecampus_copa_3530257.html))
* [Pome fruits](https://uni-bonn.sciebo.de/s/jZYjDaQZPLllQpz) (password [here](https://ecampus.uni-bonn.de/goto_ecampus_copa_3530257.html))

As supplementary material, we also offer two videos on sweet cherry bloom and apple varieties recorded by our HortiWood team:

* [Apple varieties](https://uni-bonn.sciebo.de/s/wrGdpRgt7GKVYzo) (password [here](https://ecampus.uni-bonn.de/goto_ecampus_copa_3530257.html))
* [Sweet cherry bloom](https://uni-bonn.sciebo.de/s/OQlxeit0brc8iH4) (password [here](https://ecampus.uni-bonn.de/goto_ecampus_copa_3530257.html))

*You need the module password from [eCampus](https://ecampus.uni-bonn.de/goto_ecampus_copa_3530257.html) to access these files.*


### Questions

1. In a few lines, describe the main difference between the fruit production systems for pome and stone fruits. Link the process occurring inside the fruit and the changes that farmers could see.
2. What are the types of sunburn usually observed in apple orchards? How could farmers avoid this problem?

## Instructions

We'll be going for a walk with you. Depending on weather conditions, the ground may be wet or muddy, and it may be raining/snowing/windy etc. Make sure to dress appropriately! 

## Literature for discussion

This week we will discuss the following paper: [Kofler et al., 2019. High crop load and low temperature delay the onset of bud initiation in apple. Scientific Reports 9, 17986.](https://doi.org/10.1038/s41598-019-54381-x)
Read the paper and discuss the tools that are used to study the mechanism of flower bud induction in apple.

Why is the understanding of the flower induction mechanism of particular importance for temperate fruit production? Please be critical while reading the work and try to find the confirmation of each key point described in the text with the data that is shown in the paper.

## Term paper topics

**Seeded vs. Seedless: Comparative physiology of parthenocarpic and seeded fruits in fruit trees**

*[Anton Milyaev](http://inresgb-lehre.iaas.uni-bonn.de/author/dr.-anton-milyaev/)*

In this paper, you will explore parthenocarpy as the development of fruits without fertilization, highlighting its occurrence in various fruit tree species (or maybe other horticultural plants) and its use in horticultural practice. The paper will review the general physiological and molecular mechanisms of parthenocarpy, compare parthenocarpic fruits with seeded fruits within the same species or cultivars, emphasizing differences in fruit set, anatomy, growth patterns, and quality traits such as size and shape. The paper will also address the practical implications of seedlessness for horticultural production, consumer preference, postharvest performance, and breeding strategies.

**Chilling requirements and global warming: Can we adjust photoperiod to compensate for winter chill in plants?**

*[Anton Milyaev](http://inresgb-lehre.iaas.uni-bonn.de/author/dr.-anton-milyaev/)*

Global warming is reducing the accumulation of chilling temperatures necessary for temperate fruit trees to break dormancy and flower properly. In this paper, you will investigate whether manipulating the photoperiod during the winter months could compensate for a lack of chilling. Review the biological and physiological processes behind photoperiod and dormancy in plants (with focus on fruit trees). Present you literature research on how light manipulation (e.g., shortened or extended daylight exposure, certain light spectra, etc.) might affect dormancy and whether the photoperiod can help adjust, reduce or replace chilling needs.

**Influences of spring frost protection on the environment**

*[Christine Schmitz](http://www.hortibonn.de/author/christine-schmitz/)*

Frost protection measures are great for reducing yield losses caused by spring frosts. But how do they influence the environment, within the orchard, in the surrounding area? You could also include social influences. Select a few frost protection measures and collect information, e.g. from scientific and practical literature, to give an overview about the side effects of frost protection.  

**Horticultural and technological approaches to enhance apple fruit coloration**

*[Christine Schmitz](http://www.hortibonn.de/author/christine-schmitz/)*

This paper will introduce apple peel coloration as a key quality trait for red and bi-colored varieties, emphasizing its role in consumer preference, market value, and classification standards. It will briefly outline the physiological and biochemical basis of fruit color development, focusing on anthocyanin biosynthesis and its regulation by light, temperature, and genetic factors. It will then discuss horticultural practices and technological measures that can enhance peel reddening. Case studies and recent experimental findings will illustrate both the challenges and effective solutions. 

**Rest breaking strategies in temperate fruit trees**

*[Eike Luedeling](http://www.hortibonn.de/author/prof.-dr.-eike-luedeling/)*

In many warm growing regions of temperate fruits, trees struggle to accumulate sufficient winter chill to break their dormancy. Climate change appears to be aggrevating this problem. Growers are therefore looking for, and in many cases already applying, strategies to artificially promote dormancy release. This term paper reviews the current state of knowledge on strategies for artificial rest-breaking and discusses the challenges and opportunities.
