# Berries
*by [Anton Milyaev](http://inresgb-lehre.iaas.uni-bonn.de/author/dr.-anton-milyaev/)*


## Materials

For this week’s session, you are required to take a look at the presentation and supplementary materials by Dr. Anton Milyaev. You can find these documents here:

* [Slides](https://uni-bonn.sciebo.de/s/fniKx0VYcAfAsbo) (password [here](https://ecampus.uni-bonn.de/goto_ecampus_copa_3530257.html))
* [Cultivation of blueberry](https://uni-bonn.sciebo.de/s/iz7dzyj4PiRO3o2) (password [here](https://ecampus.uni-bonn.de/goto_ecampus_copa_3530257.html))
* [Cultivation of raspberry](https://uni-bonn.sciebo.de/s/HxcQwPh4bdZdhjk) (password [here](https://ecampus.uni-bonn.de/goto_ecampus_copa_3530257.html))
* [Cultivation of currants](https://uni-bonn.sciebo.de/s/Tl9f006zi5kQf0R) (password [here](https://ecampus.uni-bonn.de/goto_ecampus_copa_3530257.html))

### Questions

1. Describe a typical training system that is used for production of cane fruits.
2. What is the main soil requirement for the cultivation of blueberries? What is the advantage of using containers for blueberry production (especially in regards to soil requirements)?

## Instructions

This week, we also expect to take you for a short field trip to visit a demonstrative cane production plot in Endenich. So, make sure to dress appropriately!

## Literature for discussion

For the berry week, we will discuss the following paper: [Zhang et al. 2010. Inhibitory effect of raspberries on starch digestive enzyme and their antioxidant properties and phenolic composition. Food Chemistry, 2: 592-599.](https://doi.org/10.1016/j.foodchem.2009.06.063) (also [here](https://uni-bonn.sciebo.de/s/VxXwNt9lFX5ZOgd), accessible with the password from [here](https://ecampus.uni-bonn.de/goto_ecampus_copa_3530257.html)).

Read the paper and discuss in the group the most prominent health benefits of raspberries in a context that is given in the corresponding publication. Please be critical while reading the work and try to find the confirmation of each key point described in the text with the data that is shown in the paper.

## Term paper topics

**Berry plants and declining bee communities: Will the berry production still be possible without pollinators?**

*[Anton Milyaev](http://inresgb-lehre.iaas.uni-bonn.de/author/dr.-anton-milyaev/)*

Many plant species rely on pollinators, such as bees and other insects, that are essential for the fertilization of flowers. Scientists currently express their concerns that year after year there are less and less insects including bees due to the intensive insecticide use in agriculture. Does the yield of berry plants (raspberries, blueberries, currents, blackberries, etc.) also depend on pollinators? If yes, to what extent? Is berry production possible without pollinating insects? In this term paper, you will investigate how pollinator presence affects the pollination efficiency, fruit set, and overall yield of berry crops, and strategies to enhance pollination.

