# Agroforestry
*by [Prajna Kasargodu Anebagilu](https://www.gartenbauwissenschaft.uni-bonn.de/author/dr.-prajna-kasargodu-anebagilu/) and [Cory Whitney](https://www.gartenbauwissenschaften.uni-bonn.de/en/staff/cory-whitney)*


Agroforestry refers to a land-use system that integrates trees or shrubs into agricultural land and/or livestock farming. By diversifying production it can generate social, economic and environmental benefits.Unlike conventional agriculture, which often separates production and ecology, agroforestry seeks to harness the interactions between these components to improve both environmental and economic outcomes. Agroforestry is increasingly recognized as one of the most promising land use options for addressing multiple Sustainable Development Goals and confronting the challenges of climate change mitigation, food security, soil degradation, decline of biodiversity and desertification.   

## Materials

The following three videos from *[Prof. Eike Luedeling](https://www.gartenbauwissenschaften.uni-bonn.de/en/staff/eike-luedeling)* will give you a first overview of what agroforestry is, what it can contribute, and what it looks like in practice:

### What is agroforestry?

<iframe width="560" height="315" src="https://www.youtube.com/embed/2o8-eWSpThk" frameborder="0" allowfullscreen></iframe>

[Here are the slides that belong to this video.](https://uni-bonn.sciebo.de/s/D6gaE6crpYLw6TZ)

### What does agroforestry contribute?

<iframe width="560" height="315" src="https://www.youtube.com/embed/w0S5xpQzmTY" frameborder="0" allowfullscreen></iframe>

[Here are the slides that belong to this video.](https://uni-bonn.sciebo.de/s/4ZYt9wpcktE3LLm)

### Agroforestry examples

<iframe width="560" height="315" src="https://www.youtube.com/embed/tzcHIHE6zXk" frameborder="0" allowfullscreen></iframe>

[Here are the slides that belong to this video.](https://uni-bonn.sciebo.de/s/Zsk1M9SIu62i27L)

### Agroforestry in the European Union

Also go through the following briefing document, developed for the European Parliament, which outlines the current situation and legal setting of agroforestry in Europe: [Agroforestry in the European Union](https://www.europarl.europa.eu/RegData/etudes/BRIE/2020/651982/EPRS_BRI(2020)651982_EN.pdf)

You can also find this [on eCampus](https://ecampus.uni-bonn.de/goto_ecampus_file_3562269_download.html).

### Questions (or rather "assignments" today)

1. Other than the three basic types of agroforestry what other classifications do you know? Name three.
2. Name seven reasons why farmers may benefit from introducing agroforestry on their farm.
<!-- 3. Briefly describe two examples of agroforestry systems (in up to three sentences each). -->
3. Name three constraints to the implementation of agroforestry in Europe.

## Instructions

<!-- This week we'll take a shot at designing an agroforestry system. You'll get more detailed instructions in class. -->
This week, building on the lecture you have listened to, we will perform a placement activity to understand different types of agroforestry systems and explore how to design them across a larger landscape considering their benefits, challenges, and inherent design features.

We will then take a closer look at the agroforestry decision-support tools developed at HortiBonn under the ReForest project.

## Literature for discussion

We're discussing the following paper:

[Tsonkova et al. 2018: Addressing farmer-perceptions and legal constraints to promote agroforestry in Germany. Agroforestry Systems 92, 1091–1103](https://link.springer.com/content/pdf/10.1007/s10457-018-0228-4.pdf)

You can also find it [on eCampus](https://ecampus.uni-bonn.de/goto_ecampus_file_3562268_download.html).

In addition - this is optional - we encourage you to take a look at the following materials:

* A paper on the perceptions of various stakeholders across Europe towards agroforestry: [Garcia de Jalon et al. 2018: How is agroforestry perceived in Europe? An assessment of positive and negative aspects by stakeholders](https://ecampus.uni-bonn.de/goto_ecampus_file_3562267_download.html)

* A selection of two chapters of a brand new textbook on agroforestry. This is the long-awaited second edition of the "An Introduction to Agroforestry" - a seminal textbook by PK Nair et al. that was first published in 1991: [An Introduction to Agroforestry](https://ecampus.uni-bonn.de/goto_ecampus_file_3562270_download.html) and the latest edition (https://link.springer.com/book/10.1007/978-3-030-75358-0)

## Term paper topics

**The challenges of agroforestry modeling**

*[Cory Whitney](https://www.gartenbauwissenschaften.uni-bonn.de/en/staff/cory-whitney)*

Modeling agroforestry systems are more complex than monocultures, so they have presented considerable challenges to the modeling community. This term paper outlines these challenges and reviews how they have been addressed in previous modeling attempts.

**Barriers to agroforestry adoption in Germany (or elsewhere)**

*[Prajna Kasargodu Anebagilu](https://www.gartenbauwissenschaft.uni-bonn.de/author/dr.-prajna-kasargodu-anebagilu/)*

Many experts agree that agroforestry systems can offer environmental, economic and social benefits to farmers. Yet adoption rates often remain low due to an array of barriers that keep farmers from integrating trees with other agricultural practices. This term paper reviews these barriers and proposed ideas for overcoming them.

**Agroforestry in Germany (or elsewhere) - present distribution expansion potential**

*[Cory Whitney](https://www.gartenbauwissenschaften.uni-bonn.de/en/staff/cory-whitney)*

Agroforestry has gained traction in many places, yet its spread in Germany (and many other countries) has been slow. This term paper reviews what types of systems exist and where they can be found (possibly using case studies). It also speculates on the potential distribution within this geographic region.
