# Global horticulture for SDGs {#SDGs}
*by [Cory Whitney](http://www.hortibonn.de/author/dr.-cory-whitney/), [Prajna Kasargodu Anebagilu](https://www.gartenbauwissenschaft.uni-bonn.de/author/dr.-prajna-kasargodu-anebagilu/), [Simone Kathrin Kriesemer](https://www.gartenbauwissenschaft.uni-bonn.de/author/dr.-simone-kathrin-kriesemer/), [Eike Luedeling](http://www.hortibonn.de/author/prof.-dr.-eike-luedeling/)*

In 2015 the United Nations Member States adopted the [2030 Agenda for Sustainable Development](https://sdgs.un.org/2030agenda). The agenda provides a blueprint for a sustainable future with 17 [Sustainable Development Goals](https://sdgs.un.org/goals) (SDGs). In this lecture we will discuss the relationship between these SDGs and global horticultural production.

## Materials

The materials for this course will include videos, live lectures, group work and discussions. 

## Questions

1. Name a potential synergy between two or more SDGs as they relate to horticultural production.
1. Answer the same question but talk about trade-offs.
1. Name one aspect of the development strategy in your country that is related to the SDGs and horticulture.


## Instructions

In our time together in the lecture we will discuss the SGDs and their relationship to horticulture. We will offer some overview and invite you to think critically about the transformations that are needed for horticulture to realistically contribute to the SDGs, and about any associated trade-offs. You will take on the role of an SDG and briefly present yourself and your targets and how they relate to horticulture. We will present you with some scenarios to explore SDGs and horticultural production. We will invite you to work in your groups to build a diagram of the SDGs and horticulture, see [Stockholm Resilience Centre](https://www.stockholmresilience.org/research/research-news/2016-06-14-the-sdgs-wedding-cake.html)

You will read up on and prepare for role playing as one of the 17 SDGs. Please review the SDGs and their targets with the [UN SDG targets map](https://maps.kontextlab.com/client/unitednations/158). Please also review the background and story of the SDGs by [The United Nations Department of Economic and Social Affairs](https://sdgs.un.org/goals). 

## Literature for discussion

We will read a review article by *Chen, Chaudhary and Mathys*. The authors describe the role of horticulture for supporting the SDGs. [Dietary Change and Global Sustainable Development Goals](https://www.frontiersin.org/journals/sustainable-food-systems/articles/10.3389/fsufs.2022.771041/full). 

## Term paper topics

**The contribution of horticulture to the Sustainable Development Goals with a specific focus on SDG 2**

*[Cory Whitney](http://www.hortibonn.de/author/dr.-cory-whitney/)*

In this term paper you will look into the various contributions horticultural production, processing and consumption make towards achieving the SDGs. You will also take a critical look into possible detrimental developments.

**The Sustainable Development Goals and German policy on agroforestry**

*[Prajna Kasargodu Anebagilu](https://www.gartenbauwissenschaft.uni-bonn.de/author/dr.-prajna-kasargodu-anebagilu/)*

In this term paper you will look into the implications of SDG relevant German policy and how it relates to horticulture, in particular agroforestry production systems. 
