# From Greenhouse Production to Plant Factories
*by [Thorsten Kraska](https://www.gartenbauwissenschaften.uni-bonn.de/en/staff/thorsten-kraska)*

Horticulture will undergo changes in their production systems. In this week we will take a closer look at greenhouse production and vertical farming. At first we will understand what a greenhouse in its principles is. We are doing this in the greenhouse at the institute. After the visit in the greenhouse we will discuss the transformation of greenhouse production into "closed environment agriculture" (CEO), alos called indoor farming, vertical farming, or plant factories. In the paper discussion we will try to answer the question: "Is Indoor Farming the solution" for feeding the world?

## Materials

* [Greenhouse Production Systems (Part 1)](https://www.youtube.com/embed/3VutZtWKFio)
* [Greenhouse Production Systems (Part 2)](https://www.youtube.com/embed/yqGOaDygS_U)


## Instructions
- Please watch both videos carefully to get a general introduction into greenhouse production systems. The videos are the basis for further discussion in the inverted classroom.\
- Pay special attention to the equipment and infrastructure of a greenhouse. We will start the week with a visit of a greenhouse at the institute to discuss and compare the information given in the videos with a real situation. A special emphasis will be given to “light” and “lighting”.\
- Following questions may help you for preparation:\
  - How is light in a greenhouse different from the field and what does it mean for plant cultivation?\
  - How are light and lighting affecting plant yield and produce quality in a greenhouse?\
  - How can the lighting be adapted to the needs of the plants?\
  - How can light and lighting be modified (management strategies, infrastructure)?\
  - What is the meaning of UV-light and far red light?\
- You will find further readings on light (especially LED) and lighting on [eCampus](https://ecampus.uni-bonn.de/goto_ecampus_fold_3575336.html).\


## Literature for discussion
Paper discussion: We will discuss the article “Wheat yield potential in controlled-environment vertical farms” by Asseng et al. (2020)(see [eCampus)](https://ecampus.uni-bonn.de/goto_ecampus_file_3575348_download.html). The article is not on a horticultural crop, but a good case study, which could be transferred to other crops, too. There are two tasks:
1. General discussion: Are indoor farm suited to produce enough staple food for a growing population and not just "baby greens" for a more healthy lifestyle?
2. Specific topic: The article is short (5 pages), but full of details and assumptions. Let us do a fact check.
Please read the article and prepare yourself for the discussion by checking at least one fact by using the cited references (1st order references) and maybe follow the path of data.

## Term paper topics

**Can plant factories safe the world?**

*[Thorsten Kraska](https://www.gartenbauwissenschaften.uni-bonn.de/en/staff/thorsten-kraska)*

In this term paper you should evaluate which crops are already produced in plant factories (here used as a general term for all indoor farms, vertical farms, or controlled environment farms) and which crops are challenging. For crops already produced in plant factories compare yields and / or energy consumption to conventional farming systems. For crops not produced so far, discuss the challenging factors within a plant factory and how they could be solved.

**For heaven`s sake use LED - the challenges in lighting**

*[Thorsten Kraska](https://www.gartenbauwissenschaften.uni-bonn.de/en/staff/thorsten-kraska)*

One main advantage of greenhouse production is control of environmental conditions. Lighting is not only responsible for plant growth and performance yielding in an horticultural produce. Lighting can also control the quality of produce, it could support plant growth depending on growth stage. So the challenge is, what is the optimal lighting? This term paper should focus on LED lighting. How could we control plant performance and quality by light?

**It's all about energy - how photovoltaic can be used for greenhouses and plant factories**

*[Thorsten Kraska](https://www.gartenbauwissenschaften.uni-bonn.de/en/staff/thorsten-kraska)*

Greenhouse production and plant factories depend on energy for light and heating. In this term paper it should be discussed which role photovoltaic will have for a more sustainable plant production. Would this makes a year-round production possible? Discover possible new trends how photovoltaic could be used in the future.

