# From Urban Horticulture to Social Gardening {#urban_hort}
*by [Thorsten Kraska](http://www.hortibonn.de/author/dr.-thorsten-kraska/)*

***still to be updated for 2023/24***

In weeks 4 ([Vertical farming]), 5 ([Greenhouse production systems & Hydroponics]), and 8 ([Disease management and protected cultivation]) we have already discussed some aspects of Urban Horticulture. A special focus was given on technology and how horticultural production will change.

This week we will give a focus on different perspectives on Urban Horticulture. Based on your knowledge we will focus on the perspectives of (1) non-professionals (laymen, consumer, society) and professionals (gardeners, industry).

## Materials {#urban_hort_materials}

The starting point is the article by Feldmann and Vogler (2019). You will find the [article in eCampus](https://ecampus.uni-bonn.de/goto_ecampus_file_2866702_download.html) with text highlighted.

Additional readings can be found in [eCampus](https://ecampus.uni-bonn.de/goto_ecampus_fold_2866704.html). You might find them helpful to explore on the topic.

All materials are available for download in [eCampus](https://ecampus.uni-bonn.de/goto_ecampus_fold_2866698.html).

## Instructions

The groups should use the material above as starting point for their perspectives:

-   Group 1: perspective of non-professionals, consumer, community, and society
-   Group 2: perspective of professionals, gardeners, farmers, retailers, industry, market

Build your own opinion based on the given perspective for the group, which you could use. For preparation you should consider the following:

-   What are the expectations of non-professionals / professionals for a successful Urban Horticulture?
-   Which elements of Urban Horticulture (e.g. cultivation systems, size, plants) do the different perspectives focus on?
-   What do non-professionals and professionals share?
-   What are the expectations of non-professionals for professional and vice versa
-   What are the challenges in Urban Horticulture?
-   What role will „digitalization" and „technology" have?
-   How do non-professionals differ from professionals and what does this mean?
-   How will roles of non-professionals and professionals change in the transition of future Urban Horticulture

During class the groups will develop a concept of Urban Horticulture from one of the two perspectives.

## Questions

-   How is Urban Horticulture defined?
-   Define "Smart cities" in the context of Urban Horticulture

## Literature for discussion

This week we will discuss two papers:

-   Group 1: [Dorr et al. (2021). Environmental impacts and resource use of urban agriculture: a systematic review and meta-analysis](https://ecampus.uni-bonn.de/goto_ecampus_file_2866761_download.html)
-   Group 2: [Payen et al. (2022): How Much Food Can We Grow in Urban Areas? Food Production and Crop Yields of Urban Agriculture: A Meta-Analysis](https://ecampus.uni-bonn.de/goto_ecampus_file_3215874_download.html)

Both articles are meta-analyses on the subject of (1) environmental impact and (2) food production in Urban Horticulture.

This week's tasks:

-   To get the essentials from the respective paper. What are the main findings? What are the main conclusions?
-   Both articles are meta-analyses. What could be achieved with this kind of study approach? Could this lead to new research directions?

In class the two groups will have about 30 minutes to discuss the paper within the group and to prepare up to 3 slides (e.g. Powerpoint) including (1) a graph or table from the paper with main findings, (2) Summary of main findings, (3) what research should be done according to the outcome of the paper, and (4) a suggestions for a research project (title only) which you would do inspired by the article.

## Term paper topics {#urban_hort_term_papers}

**24. Back to the roots...**

[*Thorsten Kraska*](http://www.hortibonn.de/author/dr.-thorsten-kraska/)

It seems that horticulture is coming back to the roots, closer to the consumer, and often back into the cities. New forms of horticultural production have been and will be developed in an urban context (e.g community gardens, rooftop greenhouses and more). In this term paper these developments will be reviewed on basis of literature. How will horticultural production in cities look like in the future? What trends can be seen right now and what is the role of horticultural sciences and practice here? (This topic is somewhat related to Vertical farming topic "... up to the skies").

**25. Urban horticulture and the society**

[*Thorsten Kraska*](http://www.hortibonn.de/author/dr.-thorsten-kraska/)

In this term paper the meaning of urban horticulture for society should be discussed. New forms of horticulture raises societal questions. Different topics are possible: (1) Is urban horticulture a common good? (2) Edible landscaping. (3) Urban horticulture and recreation. (4) Bring in your own topic. The aim of this term paper is to think out of the box of "production" to explore the meaning of horticulture for humans and society.
