# New plants for a future-competent horticultural production {#new_plants}
*by [Thorsten Kraska](http://www.hortibonn.de/author/dr.-thorsten-kraska/)*

***still to be updated for 2023/24***

Vegetables - what a set of topics to cover in two 90 minute sessions.

Instead of getting a vague overview of vegetable production as a whole, we focus on two of the many sub-areas of vegetable production that are currently attracting a great deal of interest:

Many vegetable farms in Germany and throughout Europe are (were?) particularly affected by the current energy crisis. The first two pieces of information below deal with this issue in different ways. We spend half of the time on Wednesday talking about this issue. Therefore, I would like to ask you to have read the materials by then and possibly read up on this topic beyond these two snippets.

We will use the second 45 minutes on Wednesday to look at another aspect. You may know that parts of our working group are particularly interested in biodiverse agricultural production systems where very different plant species grow on the same piece of land. We are quite confident that this can be a way to do sustainable intensive agriculture. The second two pieces of information deal with such complex horticultural production systems.

## Materials

1. [news article on the effects of the energy crisis on vegetable producers and production](https://www.reuters.com/world/europe/europes-vegetable-farmers-warn-shortages-energy-crisis-bites-2022-09-22/)
1.  [very recent article, reaction to the German energy cost subsidies.](https://www.gabot.de/gemueseobst/news-gemuese-obst/preisbremsen-erleichterung-beim-gartenbau-420186.html)
1. [Video](https://www.3sat.de/wissen/nano/220912-roboter-nano-100.html) (Video language: German, English transcipt below)
1.  [A recent highly-cited study looking at agrivoltaic systems (photovoltaic + crops and/or vegetables) in Germany. Includes a brief description of the Land Equivalent Ratio (LER) concept.](https://ecampus.uni-bonn.de/goto_ecampus_file_2873408_download.html)


## Instructions

Guiding questions to think about before our meeting on Wednesday:

* Vegetable production in the light of the current energy crisis
  -	What types of production systems do you expect to be hit hardest by the high energy prices?
  - Isn't it more reasonable to produce vegetables for the European winter market in northern Africa?
  - should the year-round availability of fresh vegetables like tomatoes and bell pepper at low prizes be a political aim in central Europe?
*	Vegetable production in complex systems
  - What are the main drivers for the rather simple produciton systems currently dominating vegetable production in Europe?
  - How can digitalization change this situation?
  - Should the existence of complex vegetable production systems be a policy objective in Europe? Why (not)?
* Meta-question: What is your impression of the sources offered in terms of their credibility and quality?

## Further reading

Here’s a loose list of material I stumbled across when preparing the lecture. You may want to look through (some of) it:

* [infos on a EU-funded study dealing i.a. with diversification of vegetable cropping systems](https://www.diverimpacts.net/case-studies/case-study-24-uk.html)
* [homepage of naturerobots, a startup working on the implementation of robotics in biodiverse microfarming environments](https://naturerobots.de/)

## Literature for discussion

Here's the paper for discussion:

* [A recent highly-cited study looking at agrivoltaic systems (photovoltaic + crops and/or vegetables) in Germany. Includes a brief description of the Land Equivalent Ratio (LER) concept.](https://ecampus.uni-bonn.de/goto_ecampus_file_2873408_download.html) (It’s the same paper as Material #4 for our Wednesday session)

## Video transcript (Material 3)

Link to video:  https://www.3sat.de/wissen/nano/220912-roboter-nano-100.html

Speaker 1 (00:01)

Gardening in systems closer to the natural systems with high-tech: robot Leroy monitors here an experimental garden of the German Research Center for Artificial Intelligence. Not in large fields with monocultures, but in a small, complex market garden, the robot will roll in the future. With a lot of experience and knowledge, such a market garden can generate more than €150,000 per hectare in a year. But it takes a lot of experience.

Speaker 2 (00:30)

Here with these systems is that they are incredibly complex. I have mixed crops, I have everything in a very small space, I have quite a lot of different crops. I have a high level of biodiversity.

Speaker 1 (00:40)

Lots of work and lots of potential for robots. In the future, it should monitor plants as they grow, detect unwanted weeds, diseases and pests at an early stage. That is the vision of the research team.

Speaker 3 (00:54)

We want to accompany the plant from the ground up, so to speak, really as baby seedlings or as seeds all the way to full-grown plants.

Speaker 1 (01:07)

How do I build nutrient-rich soil? What plants are suitable neighbors in a market garden? What beneficial insects help fight disease? Many know that gardeners learn as they go, through experience.

Speaker 2 (01:20)

And I remember it from my past. Nothing is as unsatisfying as feeling like you're working in the garden all day and still can't get it done.

Speaker 1 (01:27)

The robot is supposed to avoid such disappointments. The plan: artificial intelligence evaluates the data from the garden, provides an overview and recommends concrete measures for the garden. The tips are intended to help the gardeners succeed as quickly as possible in growing vegetables in market gardens, which is considerably more time-consuming than conventional production.

Speaker 4 (01:47)

You can think of it as basically like the new invention of printing, so to speak. Back then, when you had certain theses or you had certain knowledge, you tried to preserve that and share that. And we would now no longer write a book, but we make machine-readable knowledge, which we make available to the users via our hardware, our robotics as well as via our software.

Speaker 1 (02:06)

And as close to nature as possible. Food is already being grown in high-tech greenhouses thanks to artificial intelligence, but in monocultures using only nutrient solution. There is also high-tech in the garden, but new habitats for animals and plants are also being created. The research team is still in the early stages. Robot Lero is a first prototype created within eight months in the workshop. Now it must learn to move autonomously and recognize the plants as well as possible with the help of artificial intelligence. Three D maps, which are repeatedly recreated, form the basis for analyzing each individual plant in detail. Next year, the robot will be rolling and collecting data at farmer Julian Plagemann's farm. The organic farmer has been growing vegetables in a small market garden here for four years. Not an easy task.

Speaker 5 (03:02)

My grandfather always said that you couldn't grow vegetables here, and now I can build up a regional supply of vegetables by building up the soil massively. That may be a model for others, perhaps for every village at some point, but we have, as far as I know in the Münsterland a vegetable self-sufficiency of 0.5% and I would like to counteract that.

Speaker 1 (03:31)

With his 1.5 hectare market garden, the organic farmer can currently feed over 60 people. He has loyal regular customers who reserve the vegetables online and pick them up themselves.

Speaker 5 (03:43)

I think making money through mass is more difficult than marketing directly in small quantities and delivering quality.

Speaker 1 (03:54)

The farmer still wants to expand his vegetable garden, but is reaching his limits and is eager to see how the robot can support him here next year. And he already has an extra wish.

Speaker 5 (04:07)

It would be conceivable, for example, to use the robot to make an inventory of the ripe vegetables, so that, for example, he doesn't have to go through the beds himself every week to see what will probably be ripe by the end of next week.

Speaker 1 (04:22)

In the future, farmers could also network to share information about diseases and pests.

Speaker 2 (04:29)

That means I can monitor pest flights. They are there, after all. If one farm has the first insect, it will soon appear on the other farms. The moment I'm more connected, I can use those networks to also install advance warning systems much more efficiently, do much smarter cooperation. I can exchange with workers and farms if I know who has what in the fields and how.

Speaker 1 (04:52)

Orchards could also be monitored by robot in the future. There are also plans to use it in viticulture. Now the research team first has to build a new second prototype. The team has also already founded a start up, would like to stand on its own two feet in 2023. They hope that through their research, more farmers will rely on small vegetable gardens in the future. 


## Term paper topics

**11. Vegetable production in Germany in the context of the current energy crisis**

*[Jan Ellenberger](http://www.hortibonn.de/author/dr.-jan-ellenberger/)*

Vegetable production - especially year-round production under glass - is extremely energy-intensive and in many parts still based on fossil fuels. What does the current energy crisis mean for domestic vegetable production? What are the farms doing, what is the political support and what prices can we expect for locally produced vegetables?

**12. Vegetables in complex production systems**

*[Jan Ellenberger](http://www.hortibonn.de/author/dr.-jan-ellenberger/)*

The purpose of this paper is to provide an overview of the integration of vegetables into complex production systems. In a global context, it becomes clear that growing similar vegetables on large areas is not the only possible form of production. Can more complex cropping systems also be successful in Germany? Do they even already exist?

