# New plants for a future-competent horticultural production
*by [Thorsten Kraska](https://www.gartenbauwissenschaften.uni-bonn.de/en/staff/thorsten-kraska)*

Instead of discussing how cultivation of established crops could be improved, this chapter is dealing with what “new” crops could be cultivated in Germany. Or how new crops could be developed. This could be plants until now underexplored or crops cultivated somewhere else in the world (but not in Germany) or emerging new crops from ancient relatives. It is about regional production of until now exotic plants.

At the end of this topic you should have a well-informed opinion, why and how new crops should be developed.


## Materials

There are no given materials for this week’s topic. It is about you to think about the topic, find “own” materials, come up with ideas. Within the class we will discuss from the scratch. In the course we will develop and explore the topic together.


## Instructions

Guiding questions to think about before our meeting on Wednesday:

- What makes a plant a “new crop”?
- How could new crops be developed? What are the sources?
- What must be considered to introduce a new crop into horticultural production?
- What type of plants could be more easily introduced, which plants might have difficulties?
- Is there a need for developing new crops?
- In which area do we need new crops (food, feed, fibres, energy)?
- Do we develop “new crops” or only new traits in established crops?
- What traits are important for future crops?
- Are new crops equal to new business opportunities?
- Must the production system be adapted to new crops?
- Could we design future crops?
- Do growers need new crops?

For the “answer” assignment you only need to address one of the above questions. But all should answer this:

- Give one example for a possible new plant / crop and tell why.


## Further reading

Here are a few articles, which might help you to start thinking about it:

- Smart horticulture as an emerging interdisciplinary field combining novel solutions: Past development, current challenges, and future perspectives [https://doi.org/10.1016/j.hpj.2023.03.015](https://doi.org/10.1016/j.hpj.2023.03.015)
- New crops on the block: effective strategies to broaden our food, fibre, and fuel repertoire in the face of increasingly volatile agricultural systems [https://doi.org/10.1093/jxb/eraf023](https://doi.org/10.1093/jxb/eraf023)


## Literature for discussion

Is it in the end all about genetics? Here is the paper for discussion:

- Can gene editing reduce postharvest waste and loss of fruit, vegetables, and ornamentals? [https://doi.org/10.1038/s41438-020-00428-4](https://doi.org/10.1038/s41438-020-00428-4)


## Term paper topics

**New Crop case study**

*[Thorsten Kraska](https://www.gartenbauwissenschaften.uni-bonn.de/en/staff/thorsten-kraska)*

Which crop could be cultivated in German, which is traditionally not grown here. Re-think horticultural production and imagine what crops could be cultivated here in future. Consider that the production system is constantly improved, new technologies will emerge. Try to find a case where a business case could be possible. Or explore a new crop and which factors have to be considered.

**Future-competent production systems**

*[Thorsten Kraska](https://www.gartenbauwissenschaften.uni-bonn.de/en/staff/thorsten-kraska)*

Think beyond classical production in the field or greenhouse, think ahead of vertical farms. What makes horticultural production sustainable, smarter for the future. What is about integration of a.i. technologies, digital tools or Internet of Things. Will new technologies overcome old obstacles of production. Where could “Horticulture” be in 10 years from now and what should it deliver to the society? Try to find pieces of evidence in the literature.
