# Robotics and Digitalization
*by [Lars Zimmermann](http://www.hortibonn.de/author/lars-zimmermann/) and [Johannes Kopton](http://www.hortibonn.de/author/johannes-kopton/)*

<!--***still to be updated for 2023/24***-->

One pressing challenge of horticulture today is the demand for more sustainable production using less inputs, while at the same time labor force is less and less available. Furthermore, production costs need to be mitigated in order to stay economically competitive.

One solution could be *automation*, i.e. using robots or other digital systems. This week, we will discuss what kinds of systems are being developed, what they may be useful (and already used) for, and what their impact on horticulture and society might be.

<!-- It seems that robotics, artificial intelligence, and digitalization are now discussed for everything. And that is true for horticulture as well. In the topic this week we will discuss not only the meaning of robotics and digitalization, but we will also discuss how it will affect horticultural production in the future. The aim is to come to a SWOT analysis of strengths, weaknesses, opportunities, and threats of new technological development -->

## Materials

First, please go through these slides on some basic concepts of robotics in horticulture: [https://uni-bonn.sciebo.de/s/QeUQIqoUeEfarqJ](https://uni-bonn.sciebo.de/s/QeUQIqoUeEfarqJ) (you can also watch this [mini lecture](https://drive.google.com/file/d/1gbIQ0PUpDOX4VhMAqpZBPd6k9CMPmdgY/view?usp=share_link) if you prefer).

Then take a look at (at least 5 of) these examples:

* Apple harvesting robots: https://www.youtube.com/watch?v=-PtqZA2enkQ
* Strawberry harvesting robot: https://www.youtube.com/watch?v=M3SGScaShhw
* General purpose orchard robot: https://www.youtube.com/watch?v=9DSNqdIUfqA
* Sweet pepper harvesting robot: https://www.youtube.com/watch?v=5chk9Sory88
* Autonomous orchard tractor: https://www.youtube.com/watch?v=OIwID7CFZ9s
* Strawberry harvesting robot: https://www.youtube.com/watch?v=Pwl9Z2h4Io4
* Tomato harvesting robot: https://www.youtube.com/watch?v=c-JduOfLEpc
* Strawberry harvesting robot: https://www.youtube.com/watch?v=OyA9XnW6BV4
* Genral purpose orchard robot: https://www.youtube.com/watch?v=7eDmr1f2mkI
* Apple harvesting robot: https://www.youtube.com/watch?v=xzOf4-WaXzE

## Instructions
Try to answer the following questions:

1. 🦾 Which sensor/actuator systems can you see? Which other sensor/actuator systems do you expect to be there?
2. ↔️ What kind of decisions (operational, tactical and strategic) could be improved by the information provided by the robot?
3. 📈 Do you expect the robot to make the production system cheaper?
4. 🌍️ Do you expect the robot to make the production system more sustainable?
5. 🧑🌾 Why would or wouldn't a farm manager decide to invest in this robot?
6. 🌳 Does the robot fit in regular production systems, or does it need/enable changes in the production system?

## Literature for discussion

In the paper discussion we will discuss this small introduction about _digitalization in horticulture_: [https://uni-bonn.sciebo.de/s/heXAgLMCgiTg1Rw](https://uni-bonn.sciebo.de/s/heXAgLMCgiTg1Rw)

Question for discussion: Is digitalization something that just happens to horticulture? Or (if not) who is driving it and why?

## Term paper topics

**Automation in Horticulture: Cutting valuable farm jobs or response to labour shortage?**

*[Lars Zimmermann](http://www.hortibonn.de/author/lars-zimmermann/), [Johannes Kopton](http://www.hortibonn.de/author/johannes-kopton/)*

Horticultural production is comparatively labour intensive. Recent advances in robotics and automatization enabled farm managers to reduce manual workload. Is this just a response to the decreased availability of seasonal farm workers from abroad, or is it rather an economic decision leaving potential farm workers unemployed? This term paper should answer the question from a social-economical perspective.

**Farm Management Information Systems (FMIS) for Orchards: benefits and trade-offs for farm managers**

*[Lars Zimmermann](http://www.hortibonn.de/author/lars-zimmermann/), [Johannes Kopton](http://www.hortibonn.de/author/johannes-kopton/)*

In recent years Farm Management Information Systems (FMIS) have become more and more powerful. Nowadays multiple such software solutions are available even for complex horticulture production. This term paper should point out reasons for using or not using FMIS, including initial expenses, daily workload, benefits of better information and decision support, data security, and other possible variables.
