# Strawberries and cane fruits
*by Christa Lankes*

The Q&A session for this topic happens on 11th May 2021 at 13:00.

Dear students,

For the topic "strawberries and cane fruits" I will provide you with the slides of my lecture and a corresponding text paper which is supposed to replace my talk. I split that up into 3 parts you will find when using the links below.
At the end of the slides’ files I add a list of questions for your self-studies. Please, write down a few lines on each of them for further purposes. I still do hope that later in term we will find an oppotunity to meet face-to-face for discussions on these questions. If not so, we will find a way to communicate online via ecampus. Therefore, please, watch the news provided this way.

Have fun with our online offers.


The lecture materials are split into two parts.

- For part one on strawberries, the slides are here: https://uni-bonn.sciebo.de/s/AZXr61ZG2G7ag6m and the accompanying text is here: https://uni-bonn.sciebo.de/s/vq8LHQbqQKUCr8b
- For part two on strawberries, the slides are here: https://uni-bonn.sciebo.de/s/tXFhz9hF13sRHOw and the accompanying text is here: https://uni-bonn.sciebo.de/s/iYx9RBxfxTTMWgT



- And for the lecture on cane fruits, the slides are here: https://uni-bonn.sciebo.de/s/A6lOkP2VZ9okfPN and the text is here: https://uni-bonn.sciebo.de/s/m7Va36BLJyMTGHP



## Questions for self-study and discussion

### Strawberries part I

1. What is necessary for flower initiation in a strawberry plant?
2. Why are most commercial cultivars named „facultative“ short day plants?
3. Sketch the perennial development cycle of a strawberry plant.
4. How can fruit size distribution be improved?
5. What is a typical cropping profile of a commercial strawberry cultivar?
6. List breeding objectives and selection criteria, respectively, for strawberry cultivars.
7. List technical terms you need further explanation for.

### Strawberries part II

8. Which measures are taken to set up high-health nuclear stock material of strawberry plants?
9. What is the harvest date of green daughter plants and waiting bed plants, respectively?
10. What is the advantage of green plants over frigo plants?
11. Describe the course of a one-year fruit production in open stands (Normalkultur).
12. Describe the course of a one-and-a-half-year fruit production in open stands.
13. What were the steps of increasing intensification in strawberry production systems?
14. Why are plastic tunnels shifted?
15. Which production factors are regulated in a year-round protected strawberry production system?
16. List technical terms you need further explanation for.

### Cane fruits

17. What are the most important bushberry or cane fruit species in Germany at present?
18. How is it feasible to supply the fresh market with raspberries from June until October?
19. Which categories of planting material are used in modern raspberry production systems?
20. Describe a production system with floricane raspberry cultivars.
21. Describe a production system with primocane raspberry cultivars.
22. What are the traits of an intensive raspberry production system?
23. List the characteristics of „longcane“ planting material.
24. What is necessary for a highbush blueberry production system?
25. How can it be intensified?
26. List technical terms you need further explanation for.
