# Orchard systems II
*by Christa Lankes*

The Q&A session for this topic happens on 01st Jun 2021 at 13:00.

## Apple production in NRW

What you’ve seen so far has been pretty general. The following materials by Christa Lankes are more specific to production in NRW. They mostly concern apple production.

Here are the slides: https://uni-bonn.sciebo.de/s/fqP8LlfRWBYZ6BT
And here is some text that you should refer to as you’re looking through these slides: https://uni-bonn.sciebo.de/s/SpaoztnhMdUixJn

## Source-sink relationships

A very important concept in orchard systems (and elsewhere in horticulture) is the relationship between sources and sinks, as Christa Lankes explains here:
https://uni-bonn.sciebo.de/s/7f1DIs4ybJIjpPc
Here is the accompanying text, to read along while looking at the slides: https://uni-bonn.sciebo.de/s/ay24RjgCT4atosC

## Cherry production in NRW

Here are some materials on cherry production in North Rhine-Westphalia:
https://uni-bonn.sciebo.de/s/rNquUQFDJjuIPbN
and the accompanying text:
https://uni-bonn.sciebo.de/s/ZRBbll9vMhL7jnS

## Nurseries in NRW

Here are slides on nursery production in NRW:
https://uni-bonn.sciebo.de/s/WZPY2iO1EtGoqqG
and here is the text that goes with them:
https://uni-bonn.sciebo.de/s/5GzPhwZTru3PHNW

## Questions for self-study and discussion

### Apple production in NRW

1. What is the most important fruit produced in North Rhine-Westphalia in recent years?
2. Why is selection work done in apple cultivars with higher priority?
3. What are the basic objectives of crop management?
4. List reasons for the ample use of the single row system in tree fruit orchards.
5. Why is frost protection of importance?
6. What can be achieved with root pruning? How is it done?
7. What is the objective of crown management?
8. How is the slender spindle trained?
9. Why does the main production zone need support?
10. Why may mechanical pruning be introduced?
11. What is a bi-tree? Why could it be interesting for commercial fruit production?
12. List technical terms you need further explanation for.

### Source-sink relationships

13. Explain the source-sink concept.
14. When do leaves change from acting as sinks to serving as sources?
15. How does dry matter partitioning in an apple tree change throughout the vegetative period?
16. What is different in apple trees with fruit load compared to trees without fruits?
17. In which month is the largest increment in growth of apple shoots to be observed?
18. What factors affect secondary shoot growth (lammas shoot)?
19. Name the periods of fruit drop.
20. What is crucial in overlapping fruit growth and flower formation?
21. Explain the importance of the growing site for yield.
22. What is decisive for June drop?
23. Why is light management important in fruit production? 
24. List technical terms you need further explanation for.

### Cherry production in NRW

25. What was the first approach in attempts to reduce crown size in cherry trees?
26. How did researchers succeed in finding dwarfing cherry rootstocks?
27. Name an example of a dwarfing rootstock?
28. What are advantages of dwarfing cherry rootstocks?
29. What are advantages of protected cultivation?
30. Why are pollen-borne viruses dangerous in commercial cherry production?
31. What is the most important measure against that danger?
32. Why did specific cherry replant problems gain importance?
33. What is „specific“ about it?
34. What are appropriate control measures?
35. List technical terms you need further explanation for.

### Nurseries in NRW

36. How are garden roses raised in the nursery?
37. What is the difference between bush or garden roses and stemroses?
38. What is the purpose of grafting ornamental trees?
39. What is the difference between solitary and avenue trees?
40. How are avenue or solitary trees prepared for transplating?
41. What special care needs to be taken for safe transportation and easy establishment in the new stand?
42. List technical terms you need further explanation for.