# Ornamentals, with case study on *Calluna*
*by Thorsten Kraska and Marius Rütt**

## Ornamentals

*by Thorsten Kraska*

This lecture was given *live* on 18th May at 17:15.

Here's a [recording of the session](https://uni-bonn.sciebo.de/s/VFlOnuIUfwNJqgH).

And [here is the pdf](https://uni-bonn.sciebo.de/s/KpgqlDpCYwbwwEn).

## *Calluna* production

*by Marius Rütt*

The Q&A session for this topic happens on 18th May 2021 at 13:00.

“The Calluna lecture should show you that today heather plants are much more than just cemetery plants. This high-value ornamental plant product is characterized by various risks in the production procedure, which we will go through together step by step. At the end of the lecture you will receive an overview of the challenges in heather cultivation and the difficulty producers face when making management decisions. You are welcome to write me at any time via Slack if you have further questions about this special production system.



Here's the recording by Marius Rütt:

<iframe width="560" height="315" src="https://www.youtube.com/embed/Ql-XDOFnDow" frameborder="0" allowfullscreen></iframe>

mp4 file for download (from Sciebo): https://uni-bonn.sciebo.de/s/EjXwkAQFsEWzGDf (and a smaller version here: https://uni-bonn.sciebo.de/s/G6Nr75ix4FJ6Rv3)

Here are the pdf slides: https://uni-bonn.sciebo.de/s/CWBHsUeo33gsU98



In the lecture I just briefly mention the work we do in hyperspectral monitoring of Calluna plants. If you want to get more content concerning this exciting research project, check out our video at the KoGa (Kompetenzzentrum Gartenbau) channel.

Here you find the German version:  
<iframe width="560" height="315" src="https://www.youtube.com/embed/9Wuv8ax65FE&t=2s" frameborder="0" allowfullscreen></iframe>

and the English version:
<iframe width="560" height="315" src="https://www.youtube.com/embed/UOxCL4BU5EA" frameborder="0" allowfullscreen></iframe>

For all videos of the KoGa channel check out: https://www.youtube.com/channel/UCF4so5HuHvmGVUZg7aDstxQ”

## Questions for self-study and discussion

### Ornamentals

1. What makes an Ornamental an ornamental? Characterize what ornamentals are
2. What are the main differences to other crops?
3. What are main breeding goals for ornamentals?
4. What are important growth factors? Try it on the example of cutted roses.
5. What is different in water demand of ornamentals to most other crops?
6. What are the main irrigation systems? Discuss advantages and disadvantages.
7. Example Hortensias: what are the differences between ball-type and laceCape-type?
8. Why are nitrogen requierments in field grown hortensias higher than in greenhouse?
9. Describe why and how Hortensias turn “blue”
10. What is the role of Aluminium in hortensia production? And what other functions does Aluminium has?
11. Which biobased products from Hortensia macrophylla var. serrata could be derived? What can these products be used for?

### Calluna

1. What are the main risks and uncertainties in *Calluna* production?
2. What does the “bud-flowering mutation” lead to?
3. What are the consequences of the “bud-flowering mutation” for farmers and potential customers?
4. How does plant breeding affect the shape of *Calluna* plants?
5. What characteristics would farmers want for *Calluna* plants if they were to breed their own heather varieties? 