# Plant health management
*by Shyam Pariyar*

The Q&A session for this topic happens on 22nd Jun 2021 at 13:00.

Managing plant health is crucial for successful horticultural production. 

In this lecture, Dr. Shyam Pariyar shares some scientific information on a very important sector of horticultural production system (HPS), i.e. plant health management. These include highlighting some of the major plant protection approaches and a critical issues of HPS, namely copper use in integrated pest management (IPM) and Organic farming. More specifically, this lecture provides some in-depth scientific information on the following topics: 

1) plant health interactions,  

2) plant health management approaches and 

3) copper use in horticulture. 

The main objectives of this lecture are to provide you with 

1) an overview on the impacts of some fungal pathogens on some selected tree fruit, staple or cash crop, vegetable crop and grapes,   

2) an overview an actual knowledge on plant health management approaches and researches used or potentially can be used in HPS, and 

3) in-depth knowledge about a critical issue of HPS, namely copper use in HPS from an ecological perspective. 

The recording of the lecture is posted [here on Sciebo](https://uni-bonn.sciebo.de/s/ZrxfHQvniB1GMaL).

The pdf version of the slides is [here](https://uni-bonn.sciebo.de/s/1mr5ugeslOrZMdl).

To retrieve the password to download these files, please visit [the eCampus page of this module](https://ecampus.uni-bonn.de/goto_ecampus_fold_2233380.html), where you can sign in with your Uni-ID. Please don't share these materials with people who are not signed up for this module.

## Questions for self-study and discussion

1. What are the factors that affect plant health interactions?
2. How do biotic and abiotic factors affect yield and quality of horticultural products? What are the trade-off?
3. What are plant health management and plant protection approaches in horticultural production systems.
4. What are the current critical issues on horticultural production systems? Why do they play a major role in a shift in the plant health management or crop protection systems?
5. Why is “Copper” such an important plant protection agent in horticultural production systems, especially in organic farming?
6. What are pros and cons of Cu-fungicide use in horticulture? What are the potential Cu reduction strategies in horticultural production system? 