# Introduction to field vegetables
*by Nazim Gruda*

## Lectures

This lecture has been recorded ahead of time. There will be a question and answers session via zoom, so make you you make notes of all questions you may have.

This year, the introductory lecture on field vegetables will focus on Cauliflower. We can't make the materials freely available, so the following links are password protected. You can get the password on the dedicated [eCampus](https://ecampus.uni-bonn.de/goto_ecampus_fold_2227865.html) site.

Here's the video for the Cauliflower lecture:
https://uni-bonn.sciebo.de/s/2vvskRMjSAObv3e

Here are all the slides as a pdf: https://uni-bonn.sciebo.de/s/pjUIMJdhWWMjlGC

Here's the pdf with addresses of seed producers: https://uni-bonn.sciebo.de/s/szFffVDzkWa1Pgp

We're talking much about asparagus this year, but here's a TV show (in German) that does:
https://uni-bonn.sciebo.de/s/40Pbs7pqqxIO6Qt

As bonus material (not relevant for the exam), here's are the slides for a lecture on asparagus production that was given last year: https://uni-bonn.sciebo.de/s/hQjrzxR1BeIyjCf

## Virtual Field Trip

We also prepared a short field trip for you that's brought to you by the HortiWood film team!

Normally, you’d now be getting rained on or suburnt, or you’d be suffering from whatever other weather we’d have been dealt on the day of the field trip. You’d also be in for a couple of boring bus rides, dusty or muddy shoes and all the other trimmings usually associated with a trip to the countryside.

But not this time around! Instead, you have the extraordinary privilege to enjoy the first ever output of HortiWood Motion Pictures – our soon-to-be-a-classic movie on “Spargelanbau”.

So let’s follow our talented and inquisitive on-site reporting team to the asparagus farm of Matthias Engels in Bornheim. Listen to the probing questions by Tim Boenigk and the captivating narration by Priska Krefting, and enjoy your their first-hand eye-witness account of how one of Germany’s signature vegetables is produced.

Sit back and relax and enjoy your field trip into the world of “Spargelanbau”: https://uni-bonn.sciebo.de/s/xZbsw0X63TtXMV5

## Questions for self-study and discussion

1. What is the nutritional importance of cauliflower?
2. What are phytochemicals?
3. Why are the preharvest conditions (location, soil, climate, cultivation, time of harvest, etc.) so important for the product quality of vegetables? Please give some examples where exogenous (preharvest) factors can influence product quality.
4. Please show some ways to produce a cauliflower rich in phytochemicals. Which eco-physiological factors and which cultivation measures influence the content of secondary ingredients?
5. What are glucosinolates?
6. What is vernalization?
7. Please give some examples of desirable and undesirable vernalization effects on vegetables? Is vernalization of cauliflower desirable? What are the requirements for this process?
8. How can we counteract the high temperatures in summer when growing vegetables?
9. Please list some advantages and disadvantages of certain soils regarding their suitability for cultivation of cauliflower.
10. Please explain the usefulness of ball volume and shape in growing vegetable seedlings.
11. Why have different young planting methods such as press pots, seedlings etc. established in vegetable production and which of them are preferred and when? Advantages and disadvantages of different procedures.
12. Please explain the key aspects of growing white asparagus (soil and the choice of the mulch).
13. What is the significance of the periodically growing of cauliflowers and how is it carried out?
14. Name the most important cultivation measures (irrigation, fertilization, plant protection, etc.) for cauliflower / asparagus.
15. Please show different reasons for using post-harvest treatments.
16. Which storage methods are particularly suitable for cauliflower?

Note that many aspects could only be covered briefly in the lecture. Please , see the sample questions as instructions for self-study (including other sources).

