name: Render and Deploy Bookdown

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pages: write
  actions: read

jobs:
  build-bookdown:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up R
        uses: r-lib/actions/setup-r@v2

      # Step 2.5: Install system dependencies (new step)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev libgeos-dev libproj-dev
      
      # Step 3: Set up Pandoc
      - name: Install Pandoc
        uses: pandoc/actions/setup@v1

      # Step 4: Install renv and restore dependencies integrated with GitHub cache
      - uses: r-lib/actions/setup-renv@v2

      # Step 5: Render Bookdown
      - name: Render Bookdown
        run: |
          R -e 'bookdown::render_book("index.Rmd")'

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
